/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetModerationClientSuccess {
  data: {
    id: number;
    name: string;
    phone: number;
    email: string;
    logo: null | string;
    project: {
      id: number;
      name: string;
      brand: {
        description: string;
        id: number;
        logo: string;
        name: string;
      }[];
    }[];
    place: {
      id: number;
      logo: string;
      name: string;
      latitude: string;
      longitude: string;
      address_kladr: string;
      region: {
        id: number;
        name: string;
      };
      brand: {
        description: string;
        id: number;
        logo: string;
        name: string;
      };
    }[];
    roles: {
      id: number;
      name: "client" | "manager" | "recruiter" | "specialist" | "supervisor";
    }[];
    change_order: null | string;
    cancel_order: null | string;
    live_order: null | string;
    change_task: null | string;
    cancel_task: null | string;
    live_task: null | string;
    repeat_bid: null | string;
    leave_bid: null | string;
    refusal_task: null | string;
    waiting_task: null | string;
    supervisors: unknown[];
    manager: unknown[];
    count_wait_bid: string;
    counterparty: unknown[];
    time_answer_bid: string;
    notification_start: string;
  }[];
  links: {
    first: string;
    last: null | string;
    prev: null | string;
    next: null | string;
  };
  meta: {
    current_page: number;
    from: number | null;
    path: string;
    per_page: number;
    to: number | null;
  };
}
