/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
 * Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
 * You can now help us improve the API whether it's by making changes to the definition itself or to the code.
 * That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * Some useful links:
 * - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 * - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.27
 */
import {
  GetInventory200,
  Order
} from '../../schemas';


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

export type getInventoryResponse200 = {
  data: GetInventory200
  status: 200
}

export type getInventoryResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200>
}

export type getInventoryResponseSuccess = (getInventoryResponse200) & {
  headers: Headers;
};
export type getInventoryResponseError = (getInventoryResponseDefault) & {
  headers: Headers;
};

export type getInventoryResponse = (getInventoryResponseSuccess | getInventoryResponseError)

export const getGetInventoryUrl = () => {




  return `/store/inventory`
}

/**
 * Returns a map of status codes to quantities.
 * @summary Returns pet inventories by status.
 */
export const getInventory = async ( options?: RequestInit): Promise<getInventoryResponse> => {

  const res = await fetch(getGetInventoryUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? GetInventory200.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as getInventoryResponse
}


export type placeOrderResponse200 = {
  data: Order
  status: 200
}

export type placeOrderResponse400 = {
  data: void
  status: 400
}

export type placeOrderResponse422 = {
  data: void
  status: 422
}

export type placeOrderResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 422>
}

export type placeOrderResponseSuccess = (placeOrderResponse200) & {
  headers: Headers;
};
export type placeOrderResponseError = (placeOrderResponse400 | placeOrderResponse422 | placeOrderResponseDefault) & {
  headers: Headers;
};

export type placeOrderResponse = (placeOrderResponseSuccess | placeOrderResponseError)

export const getPlaceOrderUrl = () => {




  return `/store/order`
}

/**
 * Place a new order in the store.
 * @summary Place an order for a pet.
 */
export const placeOrder = async (order?: Order, options?: RequestInit): Promise<placeOrderResponse> => {

  const res = await fetch(getPlaceOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(order)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? Order.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as placeOrderResponse
}


export type getOrderByIdResponse200ApplicationJson = {
  data: Order
  status: 200
}

export type getOrderByIdResponse200ApplicationXml = {
  data: Order
  status: 200
}

export type getOrderByIdResponse400 = {
  data: void
  status: 400
}

export type getOrderByIdResponse404 = {
  data: void
  status: 404
}

export type getOrderByIdResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type getOrderByIdResponseSuccess = (getOrderByIdResponse200ApplicationJson | getOrderByIdResponse200ApplicationXml) & {
  headers: Headers;
};
export type getOrderByIdResponseError = (getOrderByIdResponse400 | getOrderByIdResponse404 | getOrderByIdResponseDefault) & {
  headers: Headers;
};

export type getOrderByIdResponse = (getOrderByIdResponseSuccess | getOrderByIdResponseError)

export const getGetOrderByIdUrl = (orderId: number,) => {




  return `/store/order/${orderId}`
}

/**
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID.
 */
export const getOrderById = async (orderId: number, options?: RequestInit): Promise<getOrderByIdResponse> => {

  const res = await fetch(getGetOrderByIdUrl(orderId),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? Order.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as getOrderByIdResponse
}


export type deleteOrderResponse200 = {
  data: void
  status: 200
}

export type deleteOrderResponse400 = {
  data: void
  status: 400
}

export type deleteOrderResponse404 = {
  data: void
  status: 404
}

export type deleteOrderResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type deleteOrderResponseSuccess = (deleteOrderResponse200) & {
  headers: Headers;
};
export type deleteOrderResponseError = (deleteOrderResponse400 | deleteOrderResponse404 | deleteOrderResponseDefault) & {
  headers: Headers;
};

export type deleteOrderResponse = (deleteOrderResponseSuccess | deleteOrderResponseError)

export const getDeleteOrderUrl = (orderId: number,) => {




  return `/store/order/${orderId}`
}

/**
 * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
 * @summary Delete purchase order by identifier.
 */
export const deleteOrder = async (orderId: number, options?: RequestInit): Promise<deleteOrderResponse> => {

  const res = await fetch(getDeleteOrderUrl(orderId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteOrderResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteOrderResponse
}


