/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetBidsSuccess {
  data: {
    id: number;
    user: {
      id: number;
      phone: number;
      email: string;
      logo: string;
      roles: {
        id: number;
        name:
          | "admin"
          | "client"
          | "manager"
          | "recruiter"
          | "specialist"
          | "supervisor";
      }[];
    };
    acceptUserId: null | {
      id: number;
      phone: number;
      email: string;
      logo: string;
    };
    status: 1 | 2 | 3 | 4 | 5;
    selfEmployed: boolean;
    place: {
      id: number;
      name: string;
      latitude: string;
      longitude: string;
      address_kladr: string;
      logo: string;
      region: {
        id: number;
        name: string;
      };
      brand: {
        id: number;
        name: string;
        logo: string;
        description: string;
      };
    };
    radius: null;
    price: null;
    priceResult: number;
    viewActivity: {
      id: number;
      name: string;
      detailName: string;
      previewText: string;
      logo: string;
      traveling: boolean;
    };
    dateStart: string;
    dateEnd: string;
    needFoto: boolean;
    dateActivity: unknown[];
  }[];
}
