/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
 * Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
 * You can now help us improve the API whether it's by making changes to the definition itself or to the code.
 * That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * Some useful links:
 * - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 * - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.27
 */
import {
  User
} from '../../schemas';
import type {
  LoginUserParams
} from '../../schemas';


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

export type createUserResponse200ApplicationJson = {
  data: User
  status: 200
}

export type createUserResponse200ApplicationXml = {
  data: User
  status: 200
}

export type createUserResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200>
}

export type createUserResponseSuccess = (createUserResponse200ApplicationJson | createUserResponse200ApplicationXml) & {
  headers: Headers;
};
export type createUserResponseError = (createUserResponseDefault) & {
  headers: Headers;
};

export type createUserResponse = (createUserResponseSuccess | createUserResponseError)

export const getCreateUserUrl = () => {




  return `/user`
}

/**
 * This can only be done by the logged in user.
 * @summary Create user.
 */
export const createUser = async (user?: User, options?: RequestInit): Promise<createUserResponse> => {

  const res = await fetch(getCreateUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(user)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? User.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as createUserResponse
}


export type createUsersWithListInputResponse200ApplicationJson = {
  data: User
  status: 200
}

export type createUsersWithListInputResponse200ApplicationXml = {
  data: User
  status: 200
}

export type createUsersWithListInputResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200>
}

export type createUsersWithListInputResponseSuccess = (createUsersWithListInputResponse200ApplicationJson | createUsersWithListInputResponse200ApplicationXml) & {
  headers: Headers;
};
export type createUsersWithListInputResponseError = (createUsersWithListInputResponseDefault) & {
  headers: Headers;
};

export type createUsersWithListInputResponse = (createUsersWithListInputResponseSuccess | createUsersWithListInputResponseError)

export const getCreateUsersWithListInputUrl = () => {




  return `/user/createWithList`
}

/**
 * Creates list of users with given input array.
 * @summary Creates list of users with given input array.
 */
export const createUsersWithListInput = async (user?: User[], options?: RequestInit): Promise<createUsersWithListInputResponse> => {

  const res = await fetch(getCreateUsersWithListInputUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(user)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? User.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as createUsersWithListInputResponse
}


export type loginUserResponse200ApplicationXml = {
  data: string
  status: 200
}

export type loginUserResponse200ApplicationJson = {
  data: string
  status: 200
}

export type loginUserResponse400 = {
  data: void
  status: 400
}

export type loginUserResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400>
}

export type loginUserResponseSuccess = (loginUserResponse200ApplicationXml | loginUserResponse200ApplicationJson) & {
  headers: Headers;
};
export type loginUserResponseError = (loginUserResponse400 | loginUserResponseDefault) & {
  headers: Headers;
};

export type loginUserResponse = (loginUserResponseSuccess | loginUserResponseError)

export const getLoginUserUrl = (params?: LoginUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/user/login?${stringifiedParams}` : `/user/login`
}

/**
 * Log into the system.
 * @summary Logs user into the system.
 */
export const loginUser = async (params?: LoginUserParams, options?: RequestInit): Promise<loginUserResponse> => {

  const res = await fetch(getLoginUserUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginUserResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as loginUserResponse
}


export type logoutUserResponse200 = {
  data: void
  status: 200
}

export type logoutUserResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200>
}

export type logoutUserResponseSuccess = (logoutUserResponse200) & {
  headers: Headers;
};
export type logoutUserResponseError = (logoutUserResponseDefault) & {
  headers: Headers;
};

export type logoutUserResponse = (logoutUserResponseSuccess | logoutUserResponseError)

export const getLogoutUserUrl = () => {




  return `/user/logout`
}

/**
 * Log user out of the system.
 * @summary Logs out current logged in user session.
 */
export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {

  const res = await fetch(getLogoutUserUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: logoutUserResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as logoutUserResponse
}


export type getUserByNameResponse200ApplicationJson = {
  data: User
  status: 200
}

export type getUserByNameResponse200ApplicationXml = {
  data: User
  status: 200
}

export type getUserByNameResponse400 = {
  data: void
  status: 400
}

export type getUserByNameResponse404 = {
  data: void
  status: 404
}

export type getUserByNameResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type getUserByNameResponseSuccess = (getUserByNameResponse200ApplicationJson | getUserByNameResponse200ApplicationXml) & {
  headers: Headers;
};
export type getUserByNameResponseError = (getUserByNameResponse400 | getUserByNameResponse404 | getUserByNameResponseDefault) & {
  headers: Headers;
};

export type getUserByNameResponse = (getUserByNameResponseSuccess | getUserByNameResponseError)

export const getGetUserByNameUrl = (username: string,) => {




  return `/user/${username}`
}

/**
 * Get user detail based on username.
 * @summary Get user by user name.
 */
export const getUserByName = async (username: string, options?: RequestInit): Promise<getUserByNameResponse> => {

  const res = await fetch(getGetUserByNameUrl(username),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? User.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as getUserByNameResponse
}


export type updateUserResponse200 = {
  data: void
  status: 200
}

export type updateUserResponse400 = {
  data: void
  status: 400
}

export type updateUserResponse404 = {
  data: void
  status: 404
}

export type updateUserResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type updateUserResponseSuccess = (updateUserResponse200) & {
  headers: Headers;
};
export type updateUserResponseError = (updateUserResponse400 | updateUserResponse404 | updateUserResponseDefault) & {
  headers: Headers;
};

export type updateUserResponse = (updateUserResponseSuccess | updateUserResponseError)

export const getUpdateUserUrl = (username: string,) => {




  return `/user/${username}`
}

/**
 * This can only be done by the logged in user.
 * @summary Update user resource.
 */
export const updateUser = async (username: string,
    user?: User, options?: RequestInit): Promise<updateUserResponse> => {

  const res = await fetch(getUpdateUserUrl(username),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(user)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateUserResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as updateUserResponse
}


export type deleteUserResponse200 = {
  data: void
  status: 200
}

export type deleteUserResponse400 = {
  data: void
  status: 400
}

export type deleteUserResponse404 = {
  data: void
  status: 404
}

export type deleteUserResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type deleteUserResponseSuccess = (deleteUserResponse200) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse400 | deleteUserResponse404 | deleteUserResponseDefault) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = (username: string,) => {




  return `/user/${username}`
}

/**
 * This can only be done by the logged in user.
 * @summary Delete user resource.
 */
export const deleteUser = async (username: string, options?: RequestInit): Promise<deleteUserResponse> => {

  const res = await fetch(getDeleteUserUrl(username),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteUserResponse
}


