/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetUserPersonalMenuSuccess {
  status: "success";
  result: {
    /**
     * @minItems 1
     */
    section: [
      {
        name: string;
        value: number;
        notification: boolean;
      },
      ...{
        name: string;
        value: number;
        notification: boolean;
      }[],
    ];
  };
}
