/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetRequisitesDataSuccess {
  status: "success";
  result: {
    bik: string;
    fio: string;
    card: string;
    account: string;
    cardDue: string;
    confidant: boolean;
    payWithCard: string;
  }[];
}
