/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DelProjectSuccess {
  data: {
    id: number;
    name: string | null;
    phone: number;
    email: string;
    logo: string | null;
    project: {
      id: number;
      name: string;
      brand: {
        id: number;
        name: string;
        logo?: string;
        description: string;
      }[];
    }[];
    place: unknown[];
    roles: {
      id: number;
      name: string;
    }[];
  };
}
