/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetCompanyAndCertificatesInquiriesSuccess {
  status: "success";
  result: {
    organization: {
      uuid: string;
      name: string;
    }[];
    certificates: {
      id: number;
      key: string;
      value: string;
    }[];
  };
}
