/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetOrdersSuccess {
  data: {
    id: number;
    place: {
      id: number;
      name: string;
      latitude: string;
      longitude: string;
      address_kladr: string;
      logo: string;
      region: {
        id: number;
        name: string;
      };
      brand: {
        id: number;
        name: string;
        logo: string;
        description: string;
      };
    };
    selfEmployed: boolean;
    status: string;
  }[];
  links?: {
    first: null | string;
    last: null | string;
    prev: null | string;
    next: null | string;
  };
  meta?: {
    current_page: number;
    from: number;
    path: string;
    per_page: number;
    to: number;
  };
}
