/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetBidSuccess {
  data: {
    id: number;
    selfEmployed: boolean;
    status: 1 | 2 | 3 | 4 | 5;
    place: {
      id: number;
      name: string;
      latitude: string;
      longitude: string;
      address_kladr: string;
      logo: string;
      region: {
        id: number;
        name: string;
      };
      brand: {
        id: number;
        name: string;
        logo: string;
        description: string;
      };
    };
    user: {
      id: number;
      phone: number;
      email: string;
      logo: string;
    };
    acceptUserId: {
      id: number;
      phone: number;
      email: string;
      logo: string;
    };
    radius: number;
    price: number;
    priceResult: number;
    viewActivity: {
      name: string;
      detailName: string;
      previewText: string;
      logo: string;
    };
    dateStart: string;
    dateEnd: string;
    needFoto: boolean;
    dateActivity: {
      timeStart: string;
      timeEnd: string;
      places: {
        id: number;
        name: string;
        latitude: string;
        longitude: string;
        address_kladr: string;
        logo: null | string;
        region: {
          id: number;
          name: string;
        };
        brand: {
          id: number;
          name: string;
          logo: null | string;
          description: string;
        };
      }[];
    }[];
  };
}
