/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
 * Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
 * You can now help us improve the API whether it's by making changes to the definition itself or to the code.
 * That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * Some useful links:
 * - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 * - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.27
 */
import {
  ApiResponse,
  Pet
} from '../../schemas';
import type {
  FindPetsByStatusParams,
  FindPetsByTagsParams,
  UpdatePetWithFormParams,
  UploadFileParams
} from '../../schemas';


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

export type updatePetResponse200ApplicationJson = {
  data: Pet
  status: 200
}

export type updatePetResponse200ApplicationXml = {
  data: Pet
  status: 200
}

export type updatePetResponse400 = {
  data: void
  status: 400
}

export type updatePetResponse404 = {
  data: void
  status: 404
}

export type updatePetResponse422 = {
  data: void
  status: 422
}

export type updatePetResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404 | 422>
}

export type updatePetResponseSuccess = (updatePetResponse200ApplicationJson | updatePetResponse200ApplicationXml) & {
  headers: Headers;
};
export type updatePetResponseError = (updatePetResponse400 | updatePetResponse404 | updatePetResponse422 | updatePetResponseDefault) & {
  headers: Headers;
};

export type updatePetResponse = (updatePetResponseSuccess | updatePetResponseError)

export const getUpdatePetUrl = () => {




  return `/pet`
}

/**
 * Update an existing pet by Id.
 * @summary Update an existing pet.
 */
export const updatePet = async (pet: Pet, options?: RequestInit): Promise<updatePetResponse> => {

  const res = await fetch(getUpdatePetUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pet)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? Pet.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as updatePetResponse
}


export type addPetResponse200ApplicationJson = {
  data: Pet
  status: 200
}

export type addPetResponse200ApplicationXml = {
  data: Pet
  status: 200
}

export type addPetResponse400 = {
  data: void
  status: 400
}

export type addPetResponse422 = {
  data: void
  status: 422
}

export type addPetResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 422>
}

export type addPetResponseSuccess = (addPetResponse200ApplicationJson | addPetResponse200ApplicationXml) & {
  headers: Headers;
};
export type addPetResponseError = (addPetResponse400 | addPetResponse422 | addPetResponseDefault) & {
  headers: Headers;
};

export type addPetResponse = (addPetResponseSuccess | addPetResponseError)

export const getAddPetUrl = () => {




  return `/pet`
}

/**
 * Add a new pet to the store.
 * @summary Add a new pet to the store.
 */
export const addPet = async (pet: Pet, options?: RequestInit): Promise<addPetResponse> => {

  const res = await fetch(getAddPetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pet)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? Pet.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as addPetResponse
}


export type findPetsByStatusResponse200ApplicationJson = {
  data: Pet[]
  status: 200
}

export type findPetsByStatusResponse200ApplicationXml = {
  data: Pet[]
  status: 200
}

export type findPetsByStatusResponse400 = {
  data: void
  status: 400
}

export type findPetsByStatusResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400>
}

export type findPetsByStatusResponseSuccess = (findPetsByStatusResponse200ApplicationJson | findPetsByStatusResponse200ApplicationXml) & {
  headers: Headers;
};
export type findPetsByStatusResponseError = (findPetsByStatusResponse400 | findPetsByStatusResponseDefault) & {
  headers: Headers;
};

export type findPetsByStatusResponse = (findPetsByStatusResponseSuccess | findPetsByStatusResponseError)

export const getFindPetsByStatusUrl = (params: FindPetsByStatusParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pet/findByStatus?${stringifiedParams}` : `/pet/findByStatus`
}

/**
 * Multiple status values can be provided with comma separated strings.
 * @summary Finds Pets by status.
 */
export const findPetsByStatus = async (params: FindPetsByStatusParams, options?: RequestInit): Promise<findPetsByStatusResponse> => {

  const res = await fetch(getFindPetsByStatusUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: findPetsByStatusResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as findPetsByStatusResponse
}


export type findPetsByTagsResponse200ApplicationJson = {
  data: Pet[]
  status: 200
}

export type findPetsByTagsResponse200ApplicationXml = {
  data: Pet[]
  status: 200
}

export type findPetsByTagsResponse400 = {
  data: void
  status: 400
}

export type findPetsByTagsResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400>
}

export type findPetsByTagsResponseSuccess = (findPetsByTagsResponse200ApplicationJson | findPetsByTagsResponse200ApplicationXml) & {
  headers: Headers;
};
export type findPetsByTagsResponseError = (findPetsByTagsResponse400 | findPetsByTagsResponseDefault) & {
  headers: Headers;
};

export type findPetsByTagsResponse = (findPetsByTagsResponseSuccess | findPetsByTagsResponseError)

export const getFindPetsByTagsUrl = (params: FindPetsByTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["tags"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }


  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pet/findByTags?${stringifiedParams}` : `/pet/findByTags`
}

/**
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags.
 */
export const findPetsByTags = async (params: FindPetsByTagsParams, options?: RequestInit): Promise<findPetsByTagsResponse> => {

  const res = await fetch(getFindPetsByTagsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: findPetsByTagsResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as findPetsByTagsResponse
}


export type getPetByIdResponse200ApplicationJson = {
  data: Pet
  status: 200
}

export type getPetByIdResponse200ApplicationXml = {
  data: Pet
  status: 200
}

export type getPetByIdResponse400 = {
  data: void
  status: 400
}

export type getPetByIdResponse404 = {
  data: void
  status: 404
}

export type getPetByIdResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type getPetByIdResponseSuccess = (getPetByIdResponse200ApplicationJson | getPetByIdResponse200ApplicationXml) & {
  headers: Headers;
};
export type getPetByIdResponseError = (getPetByIdResponse400 | getPetByIdResponse404 | getPetByIdResponseDefault) & {
  headers: Headers;
};

export type getPetByIdResponse = (getPetByIdResponseSuccess | getPetByIdResponseError)

export const getGetPetByIdUrl = (petId: number,) => {




  return `/pet/${petId}`
}

/**
 * Returns a single pet.
 * @summary Find pet by ID.
 */
export const getPetById = async (petId: number, options?: RequestInit): Promise<getPetByIdResponse> => {

  const res = await fetch(getGetPetByIdUrl(petId),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? Pet.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as getPetByIdResponse
}


export type updatePetWithFormResponse200ApplicationJson = {
  data: Pet
  status: 200
}

export type updatePetWithFormResponse200ApplicationXml = {
  data: Pet
  status: 200
}

export type updatePetWithFormResponse400 = {
  data: void
  status: 400
}

export type updatePetWithFormResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400>
}

export type updatePetWithFormResponseSuccess = (updatePetWithFormResponse200ApplicationJson | updatePetWithFormResponse200ApplicationXml) & {
  headers: Headers;
};
export type updatePetWithFormResponseError = (updatePetWithFormResponse400 | updatePetWithFormResponseDefault) & {
  headers: Headers;
};

export type updatePetWithFormResponse = (updatePetWithFormResponseSuccess | updatePetWithFormResponseError)

export const getUpdatePetWithFormUrl = (petId: number,
    params?: UpdatePetWithFormParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pet/${petId}?${stringifiedParams}` : `/pet/${petId}`
}

/**
 * Updates a pet resource based on the form data.
 * @summary Updates a pet in the store with form data.
 */
export const updatePetWithForm = async (petId: number,
    params?: UpdatePetWithFormParams, options?: RequestInit): Promise<updatePetWithFormResponse> => {

  const res = await fetch(getUpdatePetWithFormUrl(petId,params),
  {
    ...options,
    method: 'POST'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? Pet.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as updatePetWithFormResponse
}


export type deletePetResponse200 = {
  data: void
  status: 200
}

export type deletePetResponse400 = {
  data: void
  status: 400
}

export type deletePetResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400>
}

export type deletePetResponseSuccess = (deletePetResponse200) & {
  headers: Headers;
};
export type deletePetResponseError = (deletePetResponse400 | deletePetResponseDefault) & {
  headers: Headers;
};

export type deletePetResponse = (deletePetResponseSuccess | deletePetResponseError)

export const getDeletePetUrl = (petId: number,) => {




  return `/pet/${petId}`
}

/**
 * Delete a pet.
 * @summary Deletes a pet.
 */
export const deletePet = async (petId: number, options?: RequestInit): Promise<deletePetResponse> => {

  const res = await fetch(getDeletePetUrl(petId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deletePetResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deletePetResponse
}


export type uploadFileResponse200 = {
  data: ApiResponse
  status: 200
}

export type uploadFileResponse400 = {
  data: void
  status: 400
}

export type uploadFileResponse404 = {
  data: void
  status: 404
}

export type uploadFileResponseDefault = {
  data: void
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type uploadFileResponseSuccess = (uploadFileResponse200) & {
  headers: Headers;
};
export type uploadFileResponseError = (uploadFileResponse400 | uploadFileResponse404 | uploadFileResponseDefault) & {
  headers: Headers;
};

export type uploadFileResponse = (uploadFileResponseSuccess | uploadFileResponseError)

export const getUploadFileUrl = (petId: number,
    params?: UploadFileParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pet/${petId}/uploadImage?${stringifiedParams}` : `/pet/${petId}/uploadImage`
}

/**
 * Upload image of the pet.
 * @summary Uploads an image.
 */
export const uploadFile = async (petId: number,
    uploadFileBody?: Blob,
    params?: UploadFileParams, options?: RequestInit): Promise<uploadFileResponse> => {

  const res = await fetch(getUploadFileUrl(petId,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/octet-stream', ...options?.headers },
    body: uploadFileBody
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  const data = contentType.includes('json') ? ApiResponse.parse(parsedBody) : parsedBody
  return { data, status: res.status, headers: res.headers } as uploadFileResponse
}


