/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 */
export type Inputs = [
  (
    | {
        inputtype: "text";
        name: string;
        value: string;
        placeholder: string;
        validation: "none" | "default";
        disabled?: true;
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "select";
        name: string;
        value: string;
        placeholder: string;
        options: {
          value: string;
          label: string;
          disabled: boolean;
          [k: string]: unknown;
        }[];
        disabled?: true;
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "radio";
        name: string;
        value: string;
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        /**
         * @minItems 1
         */
        options: [
          {
            value: string;
            label: string;
            disabled: boolean;
            icon?: "telegram" | "viber" | "whatsapp";
            [k: string]: unknown;
          },
          ...{
            value: string;
            label: string;
            disabled: boolean;
            icon?: "telegram" | "viber" | "whatsapp";
            [k: string]: unknown;
          }[],
        ];
        [k: string]: unknown;
      }
    | {
        inputtype: "checkboxMultiple";
        name: string;
        value: string[];
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        /**
         * @minItems 1
         */
        options: [
          {
            value: string;
            label: string;
            disabled: boolean;
            [k: string]: unknown;
          },
          ...{
            value: string;
            label: string;
            disabled: boolean;
            [k: string]: unknown;
          }[],
        ];
        [k: string]: unknown;
      }
    | {
        inputtype: "photoCheckbox";
        name: string;
        value: string[];
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        /**
         * @minItems 1
         */
        options: [
          {
            value: string;
            label: string;
            disabled: boolean;
            img: string;
            text?: string;
            details?: {
              text: string;
              details: string;
              img: string;
              link?: {
                text: string;
                path: string;
                type: "internal" | "external";
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          },
          ...{
            value: string;
            label: string;
            disabled: boolean;
            img: string;
            text?: string;
            details?: {
              text: string;
              details: string;
              img: string;
              link?: {
                text: string;
                path: string;
                type: "internal" | "external";
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          }[],
        ];
        [k: string]: unknown;
      }
    | {
        inputtype: "checkbox";
        name: string;
        value: boolean;
        label: string;
        validation: "none" | "checked" | "unchecked";
        heading?: string;
        error?: string;
        status?: "warning";
        disabled?: true;
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "file";
        name: string;
        value: string;
        placeholder: string;
        validation: "none" | "default";
        url: string;
        disabled?: true;
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        drawerInfo?: {
          text?: string;
          images?: string[];
        };
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "photo";
        name: string;
        value: string;
        validation: "none" | "default";
        url: string;
        disabled?: true;
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
  ),
  ...(
    | {
        inputtype: "text";
        name: string;
        value: string;
        placeholder: string;
        validation: "none" | "default";
        disabled?: true;
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "select";
        name: string;
        value: string;
        placeholder: string;
        options: {
          value: string;
          label: string;
          disabled: boolean;
          [k: string]: unknown;
        }[];
        disabled?: true;
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "radio";
        name: string;
        value: string;
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        /**
         * @minItems 1
         */
        options: [
          {
            value: string;
            label: string;
            disabled: boolean;
            icon?: "telegram" | "viber" | "whatsapp";
            [k: string]: unknown;
          },
          ...{
            value: string;
            label: string;
            disabled: boolean;
            icon?: "telegram" | "viber" | "whatsapp";
            [k: string]: unknown;
          }[],
        ];
        [k: string]: unknown;
      }
    | {
        inputtype: "checkboxMultiple";
        name: string;
        value: string[];
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        /**
         * @minItems 1
         */
        options: [
          {
            value: string;
            label: string;
            disabled: boolean;
            [k: string]: unknown;
          },
          ...{
            value: string;
            label: string;
            disabled: boolean;
            [k: string]: unknown;
          }[],
        ];
        [k: string]: unknown;
      }
    | {
        inputtype: "photoCheckbox";
        name: string;
        value: string[];
        validation: "none" | "default";
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        /**
         * @minItems 1
         */
        options: [
          {
            value: string;
            label: string;
            disabled: boolean;
            img: string;
            text?: string;
            details?: {
              text: string;
              details: string;
              img: string;
              link?: {
                text: string;
                path: string;
                type: "internal" | "external";
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          },
          ...{
            value: string;
            label: string;
            disabled: boolean;
            img: string;
            text?: string;
            details?: {
              text: string;
              details: string;
              img: string;
              link?: {
                text: string;
                path: string;
                type: "internal" | "external";
                [k: string]: unknown;
              };
              [k: string]: unknown;
            };
            [k: string]: unknown;
          }[],
        ];
        [k: string]: unknown;
      }
    | {
        inputtype: "checkbox";
        name: string;
        value: boolean;
        label: string;
        validation: "none" | "checked" | "unchecked";
        heading?: string;
        error?: string;
        status?: "warning";
        disabled?: true;
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "file";
        name: string;
        value: string;
        placeholder: string;
        validation: "none" | "default";
        url: string;
        disabled?: true;
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        drawerInfo?: {
          text?: string;
          images?: string[];
        };
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
    | {
        inputtype: "photo";
        name: string;
        value: string;
        validation: "none" | "default";
        url: string;
        disabled?: true;
        heading?: string;
        error?: string;
        status?: "warning";
        dividerTop?: true;
        dividerBottom?: true;
        helperInfo?: {
          text?: string;
          link?: {
            text: string;
            path: string;
            type: "internal" | "external";
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      }
  )[],
];
