/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetModerationSingleClientSuccess {
  data: {
    id: number;
    name: string;
    phone: number;
    email: string;
    logo: null | string;
    project: {
      id: number;
      name: string;
      brand: {
        description: string;
        id: number;
        logo: string;
        name: string;
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    place: {
      id: number;
      logo: string;
      name: string;
      latitude: string;
      longitude: string;
      address_kladr: string;
      region: {
        id: number;
        name: string;
        [k: string]: unknown;
      };
      brand: {
        description: string;
        id: number;
        logo: string;
        name: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    roles: {
      id: number;
      name:
        | "admin"
        | "client"
        | "manager"
        | "recruiter"
        | "specialist"
        | "supervisor";
      [k: string]: unknown;
    }[];
    change_order: null | string;
    cancel_order: null | string;
    live_order: null | string;
    change_task: null | string;
    cancel_task: null | string;
    live_task: null | string;
    repeat_bid: null | string;
    leave_bid: null | string;
    refusal_task: null | string;
    waiting_task: null | number;
    supervisors: {
      id: number;
      phone: number;
      email: string;
      logo: string;
      roles: {
        id: number;
        name:
          | "admin"
          | "client"
          | "manager"
          | "recruiter"
          | "specialist"
          | "supervisor";
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    manager: unknown[];
    count_wait_bid: number;
    counterparty: unknown[];
    time_answer_bid: number;
    notification_start: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
